house_prices:  # https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data
  train_dataset: C:\data\spbu_dfs_ml101\house_prices\train.csv
  test_dataset: C:\data\spbu_dfs_ml101\house_prices\test.csv
wdbc: C:\data\spbu_dfs_ml101\wdbc\data.csv  # https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data/
mushrooms: C:\data\spbu_dfs_ml101\mushrooms\mushrooms.csv  # https://www.kaggle.com/datasets/uciml/mushroom-classification
flow_cytometry: C:\data\2spbu_dfs_ml101\flow_cytometry
